### ISSUE TITLE
Wrong mysql module when using php 5.3

### ISSUE THREAD

**Issue by azinck** [forumone/generator-web-starter#47] opened 2016-05-03 21:28 UTC
drupal.yaml specifies mysqlnd when it should be mysql.

**Comment by wwhurley** [comment] 2016-09-08 01:48
Duplicate of #48

**Closed by wwhurley** 2016-09-08 01:48 UTC

**Comment by azinck** [comment] 2016-09-08 01:49
Apparently I was very persistent here.  Haha.  Thanks William.
