### ISSUE TITLE
modify the theme directory in package.json

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/generator-web-starter#20] opened 2015-07-17 16:09 UTC
Seems like a natural step.

**Comment by wwhurley** [comment] 2015-07-17 16:10
I believe the theme folder is in the package.json file.

**Comment by ohthehugemanatee** [comment] 2015-07-17 17:08
totally correct.

**Comment by wwhurley** [comment] 2016-02-09 22:12
Duplicate of #29.

**Closed by wwhurley** 2016-02-09 22:12 UTC
Labels: enhancement
