### ISSUE TITLE
Empty plugins list while running generator

### ISSUE THREAD

**Issue by arh1** [forumone/generator-web-starter#27] opened 2015-09-30 21:07 UTC
I'm not seeing any plugins listed while running the generator. If I press [space] from this prompt, it causes an error. If I press [enter] I get a vanilla copy of the web-starter files without the project files.

Pressing [space]
```
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ yo web-starter
? Project name: Test
? Repository clone URL: https://github.com/forumone/Gates-GrandChallenges-Dev.git
? Select plugins: (Press <space> to select)



/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'checked' of undefined
    at Prompt.toggleChoice (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:222:50)
    at Prompt.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:217:10)
    at Prompt.handleKeypress (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:184:3)
    at Prompt.onSpaceKey (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:216:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ 
```

Pressing [enter]
```
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ yo web-starter
? Project name: Test
? Repository clone URL: https://github.com/forumone/Gates-GrandChallenges-Dev.git
? Select plugins: 
? Version: 1.1.x
     info ... Fetching https://github.com/forumone/web-starter/archive/1.1.x.tar.gz ...
     info This might take a few moments
.✔ Done in /home/ahieb/.cache/yeoman/forumone/web-starter/1.1.x
(!) #expand() is deprecated. Use the glob module.
(!) #expandFiles() is deprecated. Use the glob module.
(!) #expand() is deprecated. Use the glob module.
   create package.json
   create .gitattributes
   create .gitignore
   create .ruby-version
   create CHANGELOG.md
[snip]
   create tasks/register/patternlab.js
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ ls -la public
total 20
drwxrwxr-x  2 ahieb ahieb 4096 Sep 30 13:59 .
drwxrwxr-x 11 ahieb ahieb 4096 Sep 30 13:59 ..
-rw-rw-r--  1 ahieb ahieb 8273 Sep 30 13:59 drush.make
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ 
```

System details:
* Ubuntu Linux
```
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ node --version
v0.10.25
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ npm --version
1.3.10
ahieb@ahieb-pc:~/develop/sandbox/web-starter$ yo --version
1.4.8
ahieb@ahieb-pc:~/develop/sandbox/web-starter$
```

Steps taken:

1. cd generator-web-starter
1. git clone git@github.com:forumone/generator-web-starter.git
1. npm install
1. sudo npm link
1. cd ../web-starter
1. sudo npm link generator-web-starter
1. yo web-starter

**Comment by knomat** [comment] 2015-10-01 20:58
@arh1 I'm running into the same issue.

System: MacOS 10.10.5

```
node --version
v0.12.4
npm --version
2.10.1
yo --version
1.4.8
```

Error Results

```
mhumphrey-mac2:Bellwether-StateOfPlay mhumphrey$ yo web-starter
? Project name: Bellwether-StateOfPlay
? Repository clone URL: https://github.com/forumone/Bellwether-StateOfPlay.git
? Select plugins: (Press <space> to select)


/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'checked' of undefined
    at Prompt.toggleChoice (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:222:50)
    at Prompt.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:217:10)
    at Prompt.handleKeypress (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:184:3)
    at Prompt.onSpaceKey (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/checkbox.js:216:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
```

**Comment by slucero** [comment] 2015-10-14 16:09
I'm seeing and able to reproduce this same issue locally. It appears that as long as the sub-generators are installed only as dependencies they aren't discoverable in `env.getGeneratorsMeta()` resulting in the empty plugin list being described. By installing one of the generator plugins explicitly I was able to see it in the list for selection.

    ❯ npm -g ls G generator
    ├─┬ generator-angular@0.12.1
    │ ├─┬ yeoman-generator@0.16.0
    ├─┬ generator-karma@1.0.0
    │ └─┬ yeoman-generator@0.19.2
    ├─┬ generator-web-starter@0.4.1
    │ ├── generator-web-starter-capistrano@0.1.0
    │ ├── generator-web-starter-drupal@0.1.0
    │ ├── generator-web-starter-puppet@0.1.0
    │ ├── generator-web-starter-wordpress@0.1.0
    │ ├─┬ yeoman-generator@0.20.3
    ├─┬ generator-web-starter-drupal@0.1.0
    │ ├─┬ yeoman-generator@0.20.3

With `generator-web-starter-drupal` installed explicitly it is discovered by the generator and offered for selection in the list while the others remain unlisted.

    ❯ yo web-starter
    ? Project name: test
    ? Repository clone URL:
    ? Select plugins: (Press <space> to select)
     Platform
    ❯◯ Drupal

**Comment by wwhurley** [comment] 2015-10-14 16:19
This appears to be related to a couple of things. One of which was caused by the sub-generator not appearing in the module when installed via NPM due to -- I believe -- the existence of the `"main"` attribute in the `package.json` file. Some of that has been resolved with commits like [`ed42ba4`](https://github.com/forumone/generator-web-starter-drupal/commit/ed42ba4bb4cb477c1b1958108d76008ce5120cda). The other issue is with the scanning for generators by Yeoman, it only looks in the global node_modules path and walking up from the current directory, see [resolver.js(34)](https://github.com/yeoman/environment/blob/master/lib/resolver.js#L34). I'm looking at ways of injecting dependencies from this project into that list to avoid having to manually install globally all of the sub-generators.

**Closed** 2015-10-14 17:22 UTC
Labels: bug

**Comment by slucero** [comment] 2015-10-14 17:26
Confirmed as resolved locally.

**Comment by arh1** [comment] 2015-10-14 18:05
Confirmed from here as well. Thanks!
